name : Movie App CI/CD
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4.2.1

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build artifact
        uses : actions/upload-artifact@v3.1.3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
